const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const sourcePath=fs.existsSync(__dirname+'/procurement.html')?__dirname+'/procurement.html':__dirname+'/../index.html';
const html=fs.readFileSync(sourcePath,'utf8');
const js=html.split('<script>')[1].split('</script>')[0];
new vm.Script(js);
const node={addEventListener(){},classList:{toggle(){}},style:{}};
const context=vm.createContext({console,Date,Map,Set,setTimeout,clearTimeout,document:{getElementById:()=>node,addEventListener(){},querySelectorAll:()=>[]},window:{addEventListener(){}}});
vm.runInContext(js.slice(0,js.lastIndexOf('(async function(){')),context);
vm.runInContext('render=()=>{}; setStatus=()=>{}',context);
(async()=>{
 let pages=[[{id:'1'}],[{id:'2'}],[]],requests=[];
 context.mockRead=async path=>{requests.push(path);return pages.shift()};
 vm.runInContext('sbFetch=mockRead',context);
 const rows=await vm.runInContext('procurementFetchAll("procurement_items?select=*&order=id.asc")',context);
 assert.equal(rows.length,2);assert.match(requests[2],/offset=2/);
 console.log('PASS: procurement loads all pages despite server page caps');
 context.mockRead=async()=>null;
 await assert.rejects(vm.runInContext('procurementFetchAll("procurement_items?select=*")',context));
 console.log('PASS: malformed responses cannot become empty successful data');
 context.status=message=>{context.message=message};
 vm.runInContext('setStatus=status; phasesSale={p1:900,p2:0,p3:0};apiGet=async()=>({items:{healthy:{done:true}},meta:{healthy:{name:"healthy"}}}); apiGetPhases=async()=>{throw new Error("simulated outage")}',context);
 await vm.runInContext('loadState()',context);
 assert.equal(vm.runInContext('phasesSale.p1',context),900);
 assert.equal(vm.runInContext('state.items.healthy.done',context),true);
 assert.match(context.message,/تحديث جزئي/);
 console.log('PASS: failed budget read retains previous amounts and healthy items');
 vm.runInContext('itemsMeta={x:{total_qty:10,unit_price:100,tax_included:false}};state={items:{x:{completedQty:3}}}',context);
 let item=vm.runInContext('calcItem("x")',context);
 assert.equal(item.line_with_tax,1150);assert.equal(item.spent_with_tax,345);assert.equal(item.remaining_with_tax,805);
 console.log('PASS: partial completion allocates cost and VAT correctly');
 vm.runInContext('state.items.x.completedQty=20',context);
 item=vm.runInContext('calcItem("x")',context);assert.equal(item.remaining_with_tax,0);assert.equal(item.completed,10);
 console.log('PASS: completed quantity cannot exceed total in calculations');
 vm.runInContext('itemsMeta.x.tax_included=true',context);
 item=vm.runInContext('calcItem("x")',context);assert.equal(item.line_tax,0);assert.equal(item.line_with_tax,1000);
 console.log('PASS: exempt items do not receive duplicate VAT');
 context.timerStub=()=>1;context.failWrite=async()=>{throw new Error('simulated save outage')};
 vm.runInContext('setTimeout=timerStub;apiPut=failWrite; pendingSaveVersions.set("x",7)',context);
 await vm.runInContext('flushQueuedSave()',context);
 assert.equal(vm.runInContext('pendingSaveVersions.get("x")',context),7);
 assert.equal(vm.runInContext('dirtyLocal',context),true);
 assert.match(context.message,/فشل الحفظ/);
 console.log('PASS: failed save retains pending edits instead of reporting success');
})().catch(e=>{console.error(e);process.exitCode=1});